# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13f1b643ef655733ccc47a75bd219337"
name = "choco-app"
handle = "choco-app-88"
application_url = "https://determined-instruction-psp-mike.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pineapples-tree.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://determined-instruction-psp-mike.trycloudflare.com/auth/callback",
  "https://determined-instruction-psp-mike.trycloudflare.com/auth/shopify/callback",
  "https://determined-instruction-psp-mike.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
